Week5Lab/Week5Lab/Controllers/Task5Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Week5Lab.Models;

namespace Week5Lab.Controllers
{
    public class Task5Controller : Controller
    {
        static readonly string marketPath = "AppData/markets.csv";
        static readonly string productPath = "AppData/products.csv";
        static readonly string productInfoPath = "AppData/productInfo.csv";
        static readonly string orderPath = "AppData/orders.csv";
      
       
        public IActionResult Task5()
        {
            Console.WriteLine("Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
            var marketStore = new MarketStore() { Path = marketPath };
            var productStore = new ProductStore() { Path = productPath };
            var productInfoStore = new ProductInfoStore() { Path = productInfoPath };

            var marketList = marketStore.GetCollection();
            var productList = productStore.GetCollection();
            var productInfoList = productInfoStore.GetCollection();

            return View(marketList);
        }
        public IActionResult Test(int ID)
        {
            Console.WriteLine("Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
            var marketStore = new MarketStore() { Path = marketPath };
            var productStore = new ProductStore() { Path = productPath };
            var productInfoStore = new ProductInfoStore() { Path = productInfoPath };

            var marketList = marketStore.GetCollection();
            var productList = productStore.GetCollection().Where(x => x.MarketId == ID);
            var productInfoList = productInfoStore.GetCollection();

            var temp1 = productList.Join(productInfoList, tempItem => tempItem.Id,
                 info => info.ProductId,

                 (tempItem, info) =>
                 new ProductAndProductInfo
                 {
                     ProductId = tempItem.Id,
                     ProductName = tempItem.Name,
                     ProductPrice = tempItem.Price,
                     ProductAmount = tempItem.Amount,
                     ProductDeliveryPeriod = tempItem.DeliveryPeriod,
                     ProductMarketId = tempItem.MarketId,
                     ProductInfoId = info.Id,
                     ProductInfoParameter = info.Parameter,
                     ProductInfoDefinition = info.Definition,
                     ProductInfoProductId = info.ProductId
                 });

            ViewData["ID"] = ID;
            return View(temp1);
        }
        public IActionResult Buy(int ID, int ProductID)
        {
            ViewData["ID"] = ID;
            ViewData["ProductID"] = ProductID;
            return View();
        }
        [HttpPost]
        public IActionResult Answer(int ProductID,int ID)
        {
            int ProduxtAmount = int.Parse(Request.Form["Amount"].ToString());

            var productStore = new ProductStore() { Path = productPath };
            var orderStore = new OrderStore() { Path = orderPath };

            var productList = productStore.GetCollection();
            var orderList = orderStore.GetCollection();

            ViewData["ID"] = ID;
            ViewData["ProductID"] = ProductID;
            if (productList.Where(x => x.Id == ProductID).First().Amount < ProduxtAmount)
            {
                ViewData["Answer"] = "Error. We don't have so many items";
            }
            else
            {
                var c = productList.Where(x => x.Id == ProductID).First();
               
                
                    int val = orderList.Where(x => x.Id == ProductID).Sum(x => x.Amount);
                    if (val + ProduxtAmount > c.Amount)
                    {
                        ViewData["Answer"] = "Error. We don't have so many items";
                    }
                    else
                    {
                    orderStore.WriteData(c.Id, c.Name, c.Price,ProduxtAmount);
                        ViewData["Answer"] = "Ok. Your request is in process";
                    }
                
            }
            return View();
        }
    }
}

Week5Lab/Week5Lab/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Week5Lab.Models;
namespace Week5Lab.Controllers
{
    public class TestController : Controller
    {
       
        static readonly string orderPath = "AppData/orders.csv";
        public IActionResult Test()
        {
            var orderStore = new OrderStore() { Path = orderPath };
            var orderList = orderStore.GetCollection();
            var val = orderList.Sum(x => x.Amount*x.Price);
            var orderCopy = orderList.GroupBy(x => x.Id).Select(y => new Order
            {
                Id = y.First().Id,
                Name = y.First().Name,
                Price = y.First().Price,
                Amount = y.Key
            });
            ViewData["TotalAmount"] = val;
            return View(orderList);
        }
    }
}

Week5Lab/Week5Lab/Views/Task5/Answer.cshtml
@{
    ViewData["Title"] = "Answer";
}

<h2>Answer</h2>

<h3>@ViewData["Answer"]</h3>
<input type="button" value="Return to products" onclick="location.href='@Url.Action("Test", "Task5",new {ID = @ViewData["ID"]})'" />

Week5Lab/Week5Lab/Views/Task5/Buy.cshtml
@model Week5Lab.Models.Product
@{
	ViewData["Title"] = "Buy";
}

<h2>Buy</h2>




@using (Html.BeginForm("Answer", "Task5", new { ProductID = @ViewData["ProductID"], ID = @ViewData["ID"] }, FormMethod.Post))
{
	@Html.TextBox("Amount");
	<input type="submit" value="OK">
}

Week5Lab/Week5Lab/Views/Task5/Task5.cshtml
@model IEnumerable<Week5Lab.Models.Market>
@{
	ViewData["Title"] = "Task5";
}

<h2>Task5</h2>
<table class="table">
	<tr>
		@foreach (var item in Model)
		{

			<td>
				<input type="button" value=@item.Name onclick="location.href='@Url.Action("Test", "Task5",new {ID = @item.ID})'" />
			</td>
		}
	</tr>
</table>

Week5Lab/Week5Lab/Views/Task5/Test.cshtml
@model IEnumerable<Week5Lab.Models.ProductAndProductInfo>
@{
	ViewData["Title"] = "Test";
}

<h2>Test</h2>
<table class="table">
	<thead>
		<tr>

			<th>ProductId</th>
			<th>ProductName</th>
			<th>ProductPrice</th>
			<th>ProductAmount</th>
			<th>DeliveryPeriod</th>
			<th>ProductMarketId</th>
			<th>InfoId</th>
			<th>Parameter</th>
			<th>Definition</th>
			<th>ProductId</th>
			<th>Buy</th>


		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
	{

		<tr>

			<td>
				@item.ProductId
			</td>
			<td>
				@item.ProductName
			</td>
			<td>
				@item.ProductPrice
			</td>
			<td>
				@item.ProductAmount
			</td>
			<td>
				@item.ProductDeliveryPeriod
			</td>
			<td>
				@item.ProductMarketId
			</td>
			<td>
				@item.ProductInfoId
			</td>
			<td>
				@item.ProductInfoParameter
			</td>
			<td>
				@item.ProductInfoDefinition
			</td>
			<td>
				@item.ProductInfoProductId
			</td>
			<td>
				<input type="button" value="Buy" onclick="location.href='@Url.Action("Buy", "Task5",new {ID = @ViewData["ID"],ProductID = @item.ProductId})'" />
			</td>
		</tr>
		
		
}
	</tbody>
</table>