Week5Lab/Week5Lab/Controllers/Task2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Week5Lab.Models;

namespace Week5Lab.Controllers
{
    
    public class Task2Controller : Controller
    {
        static readonly string marketPath = "AppData/markets.csv";
        static readonly string productPath = "AppData/products.csv";
        static readonly string productInfoPath = "AppData/productInfo.csv";

        public IActionResult Task2()
        {
            Console.WriteLine("Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
            var marketStore = new MarketStore() { Path = marketPath };
            var productStore = new ProductStore() { Path = productPath };
            var productInfoStore = new ProductInfoStore() { Path = productInfoPath };

            var marketList = marketStore.GetCollection();
            var productList = productStore.GetCollection();
            var productInfoList = productInfoStore.GetCollection();

            return View(marketList);
        }
        
        public IActionResult Test(int ID)
        {
            Console.WriteLine("Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
            var marketStore = new MarketStore() { Path = marketPath };
            var productStore = new ProductStore() { Path = productPath };
            var productInfoStore = new ProductInfoStore() { Path = productInfoPath };

            var marketList = marketStore.GetCollection();
            var productList = productStore.GetCollection().Where(x => x.MarketId == ID);
            var productInfoList = productInfoStore.GetCollection();
            
            var temp1 = productList.Join(productInfoList, tempItem => tempItem.Id,
                 info => info.ProductId,

                 (tempItem, info) =>
                 new ProductAndProductInfo
                 {
                     ProductId = tempItem.Id,
                     ProductName = tempItem.Name,
                     ProductPrice = tempItem.Price,
                     ProductAmount = tempItem.Amount,
                     ProductDeliveryPeriod = tempItem.DeliveryPeriod,
                     ProductMarketId = tempItem.MarketId,
                     ProductInfoId = info.Id,
                     ProductInfoParameter = info.Parameter,
                     ProductInfoDefinition = info.Definition,
                     ProductInfoProductId = info.ProductId
                 });

            ViewData["ID"] = ID;
            return View(temp1);
        }
        public IActionResult SortedByPrice(int ID)
        {
            Console.WriteLine("Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
            var marketStore = new MarketStore() { Path = marketPath };
            var productStore = new ProductStore() { Path = productPath };
            var productInfoStore = new ProductInfoStore() { Path = productInfoPath };

            var marketList = marketStore.GetCollection();
            var productList = productStore.GetCollection().Where(x => x.MarketId == ID);
            var productInfoList = productInfoStore.GetCollection();

            var temp1 = productList.Join(productInfoList, tempItem => tempItem.Id,
                 info => info.ProductId,

                 (tempItem, info) =>
                 new ProductAndProductInfo
                 {
                     ProductId = tempItem.Id,
                     ProductName = tempItem.Name,
                     ProductPrice = tempItem.Price,
                     ProductAmount = tempItem.Amount,
                     ProductDeliveryPeriod = tempItem.DeliveryPeriod,
                     ProductMarketId = tempItem.MarketId,
                     ProductInfoId = info.Id,
                     ProductInfoParameter = info.Parameter,
                     ProductInfoDefinition = info.Definition,
                     ProductInfoProductId = info.ProductId
                 });

            ViewData["ID"] = ID;
            return View(temp1.OrderBy(x => x.ProductPrice));
        }
        public IActionResult SortedByAmount(int ID)
        {
           
            var marketStore = new MarketStore() { Path = marketPath };
            var productStore = new ProductStore() { Path = productPath };
            var productInfoStore = new ProductInfoStore() { Path = productInfoPath };

            var marketList = marketStore.GetCollection();
            var productList = productStore.GetCollection().Where(x => x.MarketId == ID);
            var productInfoList = productInfoStore.GetCollection();

            var temp1 = productList.Join(productInfoList, tempItem => tempItem.Id,
                 info => info.ProductId,

                 (tempItem, info) =>
                 new ProductAndProductInfo
                 {
                     ProductId = tempItem.Id,
                     ProductName = tempItem.Name,
                     ProductPrice = tempItem.Price,
                     ProductAmount = tempItem.Amount,
                     ProductDeliveryPeriod = tempItem.DeliveryPeriod,
                     ProductMarketId = tempItem.MarketId,
                     ProductInfoId = info.Id,
                     ProductInfoParameter = info.Parameter,
                     ProductInfoDefinition = info.Definition,
                     ProductInfoProductId = info.ProductId
                 });

            ViewData["ID"] = ID;
            return View(temp1.OrderBy(x => x.ProductAmount));
        }
    }
}

Week5Lab/Week5Lab/Controllers/Task3Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Week5Lab.Models;

namespace Week5Lab.Controllers
{
    public class Task3Controller : Controller
    {
        static readonly string marketPath = "AppData/markets.csv";
        static readonly string productPath = "AppData/products.csv";
        static readonly string productInfoPath = "AppData/productInfo.csv";

        
        public IActionResult Task3()
        {
            var productStore = new ProductStore() { Path = productPath };
            var productInfoStore = new ProductInfoStore() { Path = productInfoPath };

            var productList = productStore.GetCollection();
            var productInfoList = productInfoStore.GetCollection();

            var temp1 = productList.Join(productInfoList, tempItem => tempItem.Id,
                info => info.ProductId,

                (tempItem, info) =>
                new ProductAndProductInfo
                {
                    ProductId = tempItem.Id,
                    ProductName = tempItem.Name,
                    ProductPrice = tempItem.Price,
                    ProductAmount = tempItem.Amount,
                    ProductDeliveryPeriod = tempItem.DeliveryPeriod,
                    ProductMarketId = tempItem.MarketId,
                    ProductInfoId = info.Id,
                    ProductInfoParameter = info.Parameter,
                    ProductInfoDefinition = info.Definition,
                    ProductInfoProductId = info.ProductId
                }).Where(x=>(x.ProductInfoParameter=="Rating"&&int.Parse(x.ProductInfoDefinition)<6));

            return View(temp1);
        }
    }
}

Week5Lab/Week5Lab/Controllers/Task4Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Week5Lab.Models;

namespace Week5Lab.Controllers
{
    public class Task4Controller : Controller
    {
        static readonly string marketPath = "AppData/markets.csv";
        static readonly string productPath = "AppData/products.csv";
        static readonly string productInfoPath = "AppData/productInfo.csv";

       
        public IActionResult Task4()
        {
            var marketStore = new MarketStore() { Path = marketPath };
            var productStore = new ProductStore() { Path = productPath };
            var productInfoStore = new ProductInfoStore() { Path = productInfoPath };

            var marketList = marketStore.GetCollection();
            var productList = productStore.GetCollection();
            var productInfoList = productInfoStore.GetCollection();
            var temp = from product in productList
                       join market in marketList on product.MarketId equals market.ID
                       select new
                       {
                           MarketID = market.ID,
                           MarketName = market.Name,
                           MarketRating = market.Rating,
                           ProductId = product.Id,
                           ProductName = product.Name,
                           ProductPrice = product.Price,
                           ProductAmount = product.Amount,
                           ProductDeliveryPeriod = product.DeliveryPeriod,
                           ProductMarketId = product.MarketId
                       };
            var temp1 = temp.Join(productInfoList, tempItem => tempItem.ProductId,
                 info => info.ProductId,

                 (tempItem, info) =>
                 new Complete
                 {
                     MarketID = tempItem.MarketID,
                     MarketName = tempItem.MarketName,
                     MarketRating = tempItem.MarketRating,
                     ProductId = tempItem.ProductId,
                     ProductName = tempItem.ProductName,
                     ProductPrice = tempItem.ProductPrice,
                     ProductAmount = tempItem.ProductAmount,
                     ProductDeliveryPeriod = tempItem.ProductDeliveryPeriod,
                     ProductMarketId = tempItem.ProductMarketId,
                     ProductInfoId = info.Id,
                     ProductInfoParameter = info.Parameter,
                     ProductInfoDefinition = info.Definition,
                     ProductInfoProductId = info.ProductId
                 });
                var xx = marketList.Select(m => new SpecialMarket
                {
                    Name = m.Name,
                    ID = m.ID,
                    Rating = m.Rating,
                    Average = temp1.Where(t => (t.MarketID == m.ID && t.ProductInfoParameter == "Rating")).Average(z => int.Parse(z.ProductInfoDefinition))
                }).Where(x => x.Rating < x.Average);
            return View(xx);
        }
    }
}

Week5Lab/Week5Lab/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Week5Lab.Models;
namespace Week5Lab.Controllers
{
    public class TestController : Controller
    {
       
        static readonly string orderPath = "AppData/orders.csv";
        public IActionResult Test()
        {
            var orderStore = new OrderStore() { Path = orderPath };
            var orderList = orderStore.GetCollection();
            var val = orderList.Sum(x => x.Amount*x.Price);
            var orderCopy = orderList.GroupBy(x => x.Id).Select(y => new Order
            {
                Id = y.First().Id,
                Name = y.First().Name,
                Price = y.First().Price,
                Amount = y.Key
            });
            ViewData["TotalAmount"] = val;
            return View(orderList);
        }
    }
}

Week5Lab/Week5Lab/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Week5Lab</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Week5Lab</a>
            </div>
            <div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a asp-area="" asp-controller="Home" asp-action="Task1">Task1</a></li>
					<li><a asp-area="" asp-controller="Task2" asp-action="Task2">Task2</a></li>
					<li><a asp-area="" asp-controller="Task3" asp-action="Task3">Task3</a></li>
					<li><a asp-area="" asp-controller="Task4" asp-action="Task4">Task4</a></li>
					<li><a asp-area="" asp-controller="Task5" asp-action="Task5">Task5</a></li>
					<li><a asp-area="" asp-controller="Test" asp-action="Test">Test</a></li>
				</ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Week5Lab</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>